[package]
name = "wasmer-examples/hono-wasmer-starter"
version = "0.1.0"
description = "Hono Website Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/hono-wasmer-starter"

[dependencies]
"wasmer/winterjs" = "^0.3"

[fs]
"/web" = "dist"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]
